[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
test = "foundry_test"

# 添加可升级合约库的路径映射
remappings = [
    "@openzeppelin/contracts-upgradeable/=node_modules/@openzeppelin/contracts-upgradeable/",
    "@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/",
]
