[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
test = "foundry_test"

remappings = [
    "@openzeppelin/contracts-upgradeable/=node_modules/@openzeppelin/contracts-upgradeable/",
    "@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/",
]

[rpc_endpoints]
bsc_testnet = "https://bsc-testnet.bnbchain.org"

[etherscan]
bsc_testnet = { key = "${ETHERSCAN_API_KEY}" }

# BSC Testnet configuration
[profile.bsc_testnet]
chain_id = 97
gas_price = 10000000000
